// Authoring helper: each row is [categoryIndex, tags, prompt, correct, wrong1, wrong2, wrong3, explanation, slides].
// The correct choice is placed by a fixed schedule so answer positions stay balanced; run once to write src/questions/*.json.
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const CATS = ['ISR Fundamentals and Components', 'Roles and Importance of ISR', 'Airborne ISR Systems', 'Ground-Based ISR Systems', 'Maritime ISR Platforms', 'Space-Based ISR Systems', 'Timeliness, Accuracy, and Fusion', 'Coverage, Persistence, and Flexibility', 'Security, Interoperability, and Ethics'];

const easy = [
[0,['surveillance'],'A Philippine Army company posts a team to watch one bridge without interruption and log every crossing. Which ISR component is this activity?','Surveillance','Reconnaissance','Intelligence','Dissemination','Slide 26 defines surveillance as the continuous observation of a target.',[26]],
[0,['reconnaissance'],'A patrol is sent to collect data that answers one specific commander question: can trucks use a jungle road? Which ISR component does this describe?','Reconnaissance','Surveillance','Intelligence','Persistence','Slide 26 defines reconnaissance as collecting data to address a specific military question.',[26]],
[0,['intelligence'],'A battalion staff builds a product by combining the results of surveillance and reconnaissance with other data. What does the lesson call this product?','Intelligence','Surveillance','Reconnaissance','A collection plan','Slide 26 defines intelligence as the result of surveillance and reconnaissance combined with other data.',[26]],
[1,['role of ISR','decision-making'],'A brigade commander asks why the unit invests in ISR. Which purpose does the lesson state?','To give commanders information that aids decision-making','To replace the commander\'s planning with automated orders','To limit intelligence to areas held by friendly forces','To avoid assessing combat effectiveness after operations','Slide 28 says ISR aims to provide information to commanders to aid decision-making.',[28]],
[1,['evaluate combat effectiveness'],'After a training strike, the staff uses ISR to judge how well the strike worked. Which stated ISR aim is being served?','Evaluating combat effectiveness','Supporting deception techniques','Alerting friendly forces to threats','Defining the operational environment','Slide 28 lists evaluating combat effectiveness as an ISR aim.',[28]],
[1,['ISR systems','unstructured data'],'A student says ISR systems are limited to large satellites. Which statement from the lesson corrects this?','ISR systems range in size from mobile devices to satellites','ISR systems are limited to manned aircraft crews','ISR systems can process structured records only','ISR systems are useful only in the air domain','Slide 29 says ISR systems range from mobile devices to satellites and use unstructured data to extract insights.',[29]],
[2,['HALE'],'A planner wants a platform that can operate extremely high for many hours since the pilot has no limitations. Which platform fits?','A high-altitude, long-endurance (HALE) vehicle','A manned reconnaissance aircraft','A ground surveillance radar','A submarine','Slide 36 says a HALE vehicle can operate extremely high for many hours since the pilot has no limitations.',[36]],
[2,['UAV','strike capability'],'Staff ask what capability UAVs offer when they carry payloads such as missiles or precision-guided ammunition. Which is stated?','A flexible and persistent strike capability supporting ground or maritime operations','Signals collection from a regular orbit','Concealed collection beneath the sea','Fixed observation from a low tower','Slide 32 describes flexible, persistent strike capability against targets identified through ISR missions.',[32]],
[2,['manned reconnaissance aircraft'],'A trainee calls manned reconnaissance aircraft a brand-new approach. What does the lesson say?','It is the traditional aerial approach, used since World War I','It is the newest approach, developed after HALE vehicles','It began with satellites and was later adapted to aircraft','It is limited to maritime missions','Slide 35 calls manned aircraft the more traditional approach, used since World War I.',[35]],
[3,['ground surveillance radar'],'A post needs a radar it can move with a vehicle. Which lesson statement supports this?','Ground surveillance radars can be fixed on a low tower or vehicle-mounted as mobile units','Ground surveillance radars are used only from satellite ground stations','Ground surveillance radars are carried only by aircraft','Ground surveillance radars operate only aboard surface ships','Slide 37 says ground surveillance radars may be fixed, usually on a low tower, or mounted on a vehicle.',[37]],
[3,['sensor networks'],'Which ground ISR resource has long been dropped behind enemy lines by Allied forces?','Fixed and mobile sensor networks','High-altitude, long-endurance vehicles','Commercial imagery products','Submarine sensors','Slide 38 says sensor networks are nothing new; sensors have been dropped behind enemy lines for decades.',[38]],
[4,['surface fleet'],'In a naval planning class, which force is described as the backbone of the Navy for maritime ISR?','The surface warfare fleet','The aviation branches','The submarine force','Space-based sensors','Slide 39 says the backbone of the Navy is its surface warfare fleet.',[39]],
[4,['submarine'],'Which maritime asset does the lesson call the most invisible asset in the entire military?','The submarine','The surface ship','The ground surveillance radar','The HALE vehicle','Slide 40 says submarines are the most invisible asset, giving them an incredible ability to gather information.',[40]],
[5,['IMINT','satellite orbit'],'A commander relies on satellite imagery alone. Which weakness does the lesson warn about?','Targets can track regular orbit cycles and avoid being seen','Satellite imagery is always blurred over the target','Satellites cannot observe large areas','Satellite imagery is blocked out over friendly territory','Slide 41 says satellites are in regular orbits, so targets can track the cycles and avoid being seen.',[41]],
[5,['MASINT'],'Which space-based discipline identifies distinctive target characteristics such as source, sender, or emitter type and location?','MASINT','IMINT','SIGINT','HUMINT','Slide 43 says MASINT identifies distinctive characteristics such as source, sender or emitter type and location.',[43]],
[5,['commercial imagery'],'A multinational partner needs imagery. Which advantage of commercial imagery does the lesson state?','It is unclassified and benefits multinational partners','It is classified and restricted to national users','It comes only from government satellites','It cannot be disseminated to partners','Slide 45 says commercial imagery products are unclassified and benefit multinational partners.',[45]],
[6,['timeliness'],'A report reaches the commander after the enemy has already moved. Which ISR principle was not met?','Timeliness','Fusion','Coverage','Security','Slide 49 says ISR prioritizes timely collection, processing and dissemination.',[49]],
[6,['accuracy'],'A report misidentifies a unit and leads to a wrong decision. Which principle was not met?','Accuracy','Persistence','Flexibility','Interoperability','Slide 50 says accuracy ensures reliable information and minimizes errors and misinterpretations.',[50]],
[6,['fusion'],'An analyst combines SIGINT, HUMINT and IMINT into one assessment. Which principle is applied?','Fusion','Coverage','Persistence','Security','Slide 51 describes fusion as using multiple sources such as SIGINT, HUMINT and IMINT.',[51]],
[7,['coverage'],'A collection plan leaves one part of the area of interest unwatched. Which principle is not met?','Coverage','Timeliness','Security','Fusion','Slide 52 says effective ISR strives for comprehensive coverage of the area of interest.',[52]],
[7,['persistence'],'A team keeps watching an area for days to detect changes and movements. Which principle does this show?','Persistence','Flexibility','Coverage','Accuracy','Slide 53 defines persistence as sustained, continuous monitoring over time.',[53]],
[7,['flexibility'],'The enemy changes routes and the S2 redirects assets and adjusts collection priorities. Which principle is applied?','Flexibility','Persistence','Interoperability','Security','Slide 54 says ISR must adapt by redirecting assets and adjusting collection priorities.',[54]],
[8,['security'],'A unit protects sensitive ISR information and assets against compromise by adversaries. Which principle is this?','Security','Interoperability','Ethical considerations','Accuracy','Slide 55 says ISR involves sensitive information and assets needing strict security measures.',[55]],
[8,['interoperability'],'Army and allied ISR assets must coordinate in a coalition operation. Which principle applies?','Interoperability','Fusion','Security','Coverage','Slide 56 says coordination and interoperability among services and allied forces are essential.',[56]],
[8,['ethical considerations'],'A team must collect within international law, rules of engagement and moral principles. Which principle governs this?','Ethical considerations','Security','Accuracy','Flexibility','Slide 57 says ethics guide collection, analysis and dissemination under law, rules of engagement and moral principles.',[57]],
];

const medium = [
[0,['surveillance','reconnaissance'],'Team A watches a compound continuously. Team B collects data to decide whether one ford can carry trucks. Which pairing of ISR components is correct?','A is surveillance; B is reconnaissance','A is reconnaissance; B is surveillance','Both are surveillance','Both are intelligence','Slide 26 separates continuous observation of a target from collection to answer a specific question.',[26]],
[0,['intelligence'],'A staff calls a single drone feed its whole intelligence estimate. Which critique fits the lesson?','Intelligence results from surveillance and reconnaissance combined with other data, so one feed is not the full product','Intelligence means only the continuous observation of one target, so a single feed satisfies it','Intelligence means only data collected to answer one specific question, which one feed can supply','One feed is intelligence because modern sensors replace the need for all other data','Slide 26 defines intelligence as the combined result of surveillance, reconnaissance and other data.',[26]],
[0,['ISR definition','processing exploitation dissemination'],'A staff plans sensors and assets but leaves out processing, exploitation and dissemination systems. Which lesson point is missed?','ISR integrates sensor and asset planning with processing, exploitation and dissemination systems','ISR concerns sensor tasking only; other staff sections own processing and dissemination','ISR supports current operations only, not future ones, so processing links are optional','ISR relies on human intelligence teams alone, so technical systems are secondary','Slide 22 defines ISR as synchronizing sensors, assets and processing, exploitation and dissemination systems.',[22]],
[1,['anticipate enemy actions','operational environment'],'A staff product predicts likely enemy actions and describes the operational environment. Which ISR aim does it serve?','Supporting military planning','Evaluating combat effectiveness','Supporting deception techniques','Holding targets at risk of attack','Slide 28 lists support to planning by anticipating enemy actions and defining the operational environment.',[28]],
[1,['deception'],'An analyst spots an enemy ruse and adjusts friendly plans, while the unit also runs its own deception. Which single ISR aim covers both?','Supporting deception techniques and counteracting enemy deception','Identifying adversary vulnerabilities and weaknesses across the theater','Alerting friendly forces to threats approaching from any direction','Holding targets at risk of attack until they can be engaged','Slide 28 pairs support for deception with counteracting enemy deception.',[28]],
[1,['adversary vulnerabilities','hold targets at risk'],'A team finds an unprotected enemy radar and then keeps it under threat of attack. Which ISR aims are served?','Identifying adversary vulnerabilities and holding targets at risk','Evaluating combat effectiveness and alerting friendly forces','Supporting deception and supporting planning','Informing commanders and evaluating effectiveness','Slide 28 lists identifying adversary vulnerabilities and holding targets at risk of attack.',[28]],
[2,['HALE','manned reconnaissance aircraft'],'A unit needs very high, long-duration coverage. Which choice and reason fit the lesson?','A HALE vehicle, since it can operate extremely high for many hours because the pilot has no limitations','A manned reconnaissance aircraft, since its crew can stay extremely high for many hours','A ground radar, since it can be dropped behind enemy lines','A manned aircraft, since World War I use proves its endurance','Slide 36 ties HALE endurance to having no pilot limitations.',[35,36]],
[2,['UAV','strike capability'],'A brief says armed UAVs are sensors with no strike role. What is the correction?','UAVs with missiles, bombs or precision-guided ammunition can engage targets identified through ISR','Only manned aircraft may engage targets found through ISR, since UAVs carry sensors alone','UAVs may never engage targets identified in ISR missions, even when carrying missiles or bombs','Only HALE vehicles give persistent strike support to ground and maritime operations','Slide 32 describes UAV payloads that engage ISR-identified targets.',[32]],
[2,['manned reconnaissance aircraft'],'An instructor corrects a student\'s timeline for manned reconnaissance aircraft. Which timeline matches the lesson?','Used since World War I and with great effect since World War II','First used in World War II and effective since World War I','Introduced with satellites and effective since the Cold War','Introduced with UAVs and effective since HALE vehicles','Slide 35 says manned aircraft have been used since World War I and with great effect since World War II.',[35]],
[3,['ground surveillance radar'],'A planner needs one radar for a fixed approach and another that can relocate. Which pairing matches the lesson?','A tower-mounted fixed radar for the approach and a vehicle-mounted mobile radar for relocation','A satellite radar for the approach and a submarine radar for relocation','A vehicle-mounted radar for the approach and a tower-mounted radar for relocation','A HALE radar for both needs','Slide 37 says ground radars are fixed, usually on a low tower, or vehicle-mounted mobile units.',[37]],
[3,['sensor networks'],'A planner calls dropping sensors behind enemy lines untested. What does the lesson say?','Sensor networks are nothing new; Allied forces have dropped sensors behind enemy lines for decades','Sensor networks are a recent development used only by space-based forces and satellite operators','Sensors have never been placed behind enemy lines because the risk of compromise is too high','Sensor networks work only when installed aboard surface ships of a naval fleet','Slide 38 says sensors have been dropped behind enemy lines for decades.',[38]],
[4,['submarine','surface fleet'],'A planner wants a covert gatherer and a foundation for naval ISR. Which pairing fits?','A submarine for covert gathering and the surface fleet as the backbone','The surface fleet for covert gathering and a submarine as the backbone','Aviation branches for covert gathering and satellites as the backbone','A submarine for both roles','Slides 39-40 name the surface fleet as backbone and the submarine as the most invisible asset.',[39,40]],
[4,['surface fleet','aviation branches'],'An exercise treats aviation as the foundation of maritime ISR. What does the lesson say?','Aviation branches are crucial, but it all begins with surface warfare','Aviation branches are not important to maritime ISR','Submarines rather than the surface fleet are the backbone','Space assets replace the surface fleet','Slide 39 says aviation is crucial but naval strength begins with the surface fleet.',[39]],
[5,['SIGINT'],'A staff plans space-based SIGINT as a stand-alone replacement for aerial and ground SIGINT. Which correction fits?','Use it in collaboration with aerial and ground-based SIGINT assets','Use it alone because its worldwide reach outranks aerial and ground SIGINT assets','Use it only as a last resort when aerial and ground assets are unavailable','Use it only for imagery tasks, leaving intercepts to aerial and ground teams','Slide 42 says space-based SIGINT is a tool used in collaboration with aerial and ground assets.',[42]],
[5,['space-based benefits','terrestrial-based benefits'],'A commander needs collection in a denied area, and separately near-real-time video with local retasking. Which pairing fits?','Space-based ISR for the denied area; company UAS for near-real-time video','Company UAS for the denied area; space-based ISR for video','Space-based ISR for both needs','Company UAS for both needs','Slide 44 lists denied-area collection for space and near-real-time video and local tasking for company UAS.',[44]],
[5,['commercial imagery'],'A partner nation needs imagery but a staff insists on classified imagery only. Which approach fits the lesson?','Use commercial imagery: unclassified, easily obtained and helpful to multinational partners','Withhold imagery because commercial products cannot help intelligence','Use classified imagery only because commercial imagery is irrelevant','Use SIGINT because imagery cannot be shared','Slide 45 lists these commercial imagery advantages.',[45]],
[6,['accuracy','timeliness'],'Report X arrived on time but misidentified a convoy. Report Y was correct but arrived after the convoy left. Which principle failed in each?','X failed accuracy; Y failed timeliness','X failed timeliness; Y failed accuracy','Both failed fusion','Both failed timeliness','Slides 49-50 pair timely delivery with reliable information.',[49,50]],
[6,['fusion'],'Which action best applies fusion?','Combining SIGINT, HUMINT and IMINT reporting before assessing the enemy position','Sending the first report received straight to the commander','Assigning all collection to one sensor for security','Waiting for full regional coverage before reporting','Slide 51 says ISR often draws on multiple intelligence sources.',[51]],
[6,['timeliness'],'Data was collected and processed but disseminated after the situation changed. Which principle applies?','Timeliness, which covers timely collection, processing and dissemination','Coverage, which requires the whole area to be watched','Security, which requires strict protection of assets','Fusion, which requires multiple sources','Slide 49 covers collection, processing and dissemination timing.',[49]],
[7,['coverage','persistence'],'Team A sees the whole area briefly each day. Team B watches one road for three days. Which principle does each show best?','A shows coverage; B shows persistence','A shows persistence; B shows coverage','A shows flexibility; B shows coverage','Both show persistence','Slides 52-53 separate area-wide coverage from sustained monitoring over time.',[52,53]],
[7,['flexibility'],'A collection plan cannot shift when the enemy changes route. Which principle is missing and what does it require?','Flexibility: quickly redirecting assets and adjusting collection priorities','Persistence: keeping every asset on the original area','Coverage: adding assets to the original area only','Security: classifying the collection plan','Slide 54 says ISR must quickly redirect assets and adjust priorities.',[54]],
[7,['persistence','flexibility'],'A commander wants continuous watch over an area and the ability to switch sensors as the enemy acts. Which principles are needed?','Persistence and flexibility','Coverage and security','Accuracy and fusion','Timeliness and interoperability','Slides 53-54 describe sustained monitoring and adaptable collection.',[53,54]],
[8,['security','interoperability'],'A unit shares raw ISR with an ally over an unsecured chat to speed coordination. Which principle conflicts, and which motivates sharing?','Security conflicts; interoperability motivates sharing','Interoperability conflicts; security motivates sharing','Ethics conflicts; accuracy motivates sharing','Fusion conflicts; coverage motivates sharing','Slides 55-56 pair protection against compromise with coordination among allies.',[55,56]],
[8,['ethical considerations'],'A team proposes intrusive surveillance beyond what law allows to improve coverage. Which principle limits it?','Ethical considerations, which follow international law, rules of engagement and moral principles','Coverage, which requires monitoring everything in the area regardless of the law','Persistence, which requires continuous monitoring of the operational area over time','Flexibility, which requires changing collection methods as the mission evolves','Slide 57 places collection under law, rules of engagement and moral principles.',[57]],
[8,['interoperability'],'Allied services in a joint task force cannot exchange ISR because formats and radios are incompatible. Which principle is at issue?','Interoperability, which requires coordination among services and allied forces','Fusion, which combines several intelligence types into one assessment','Security, which protects sensitive assets against compromise by adversaries','Persistence, which sustains continuous monitoring of the area over time','Slide 56 stresses interoperability in joint and coalition environments.',[56]],
];

const hard = [
[0,['surveillance','reconnaissance','intelligence'],'A brigade must continuously observe a hospital compound, learn whether a footbridge holds vehicles, and give the commander a product that combines both results with SIGINT. Which assignment of terms is correct?','Surveillance for the compound, reconnaissance for the footbridge, intelligence for the combined product','Reconnaissance for the compound, surveillance for the footbridge, intelligence for the combined product','Intelligence for the compound, surveillance for the footbridge, reconnaissance for the combined product','Surveillance for both tasks, reconnaissance for the combined product','Slide 26 defines all three components.',[26]],
[0,['ISR definition','processing exploitation dissemination'],'Sensors collect useful data for a brigade, but no processing, exploitation or dissemination link reaches the commander. The S3 says ISR did its job. Which assessment is best?','Incomplete: ISR must synchronize sensors, assets and processing, exploitation and dissemination systems in support of operations','Complete: collection by sensors is all that ISR requires of the staff and its systems','Complete: intelligence is the product of collection, so processing links do not affect the result','Incomplete only because too few human intelligence teams were used in the collection plan','Slide 22 defines ISR as an integrated activity spanning sensors, assets and PED systems.',[22]],
[0,['ISR sources','ISR assets'],'A commander asks which claim about ISR sources and assets is supported by the lesson.','Sources include electronic communications, optical, radar and infrared imaging, and assets include human intelligence teams','Sources are limited to optical imaging alone, and human intelligence teams are not ISR assets','Assets are limited to satellites and unmanned aircraft, excluding ground, sea and human teams','Radar and infrared are excluded because ISR relies on electronic communications only','Slide 23 lists these sources and assets.',[23]],
[1,['anticipate enemy actions','adversary vulnerabilities','deception'],'Before an offensive, a brigade wants to predict enemy reaction, find where the enemy is weakest, and detect enemy deception. Which ISR aims match?','Anticipating enemy actions, identifying adversary vulnerabilities, counteracting deception','Evaluating combat effectiveness, holding targets at risk, alerting friendly forces','Alerting friendly forces, evaluating effectiveness, defining the environment','Holding targets at risk, supporting deception, evaluating effectiveness','Slide 28 lists all three aims.',[28]],
[1,['ISR systems','unstructured data'],'A staff receives unstructured imagery, text and signals feeds from small mobile devices and a satellite. Which statement is most consistent with the lesson?','ISR systems from mobile devices to satellites use unstructured data to extract insights that speed better decisions','ISR systems process only structured data and ignore feeds from small mobile devices','Only large satellites produce insights that are usable for commanders in the field','Faster information flow tends to slow decision-making because staffs are overloaded','Slide 29 describes these ISR systems and their insights.',[29]],
[1,['support to planning','evaluate combat effectiveness'],'Higher headquarters wants ISR to support planning, but the staff supplies only post-attack combat-effectiveness assessments. Which is the gap?','Support to planning is missing; evaluating effectiveness is only one stated aim','No gap: combat-effectiveness assessment fulfills every ISR aim','No gap: planning support is an operations task, not an ISR aim','The gap is deception support, the only aim tied to planning','Slide 28 lists planning support and evaluation as separate aims.',[28]],
[2,['HALE','UAV'],'A task force needs long, high-altitude overhead coverage and a way to engage targets found through ISR. Which combination fits?','A HALE platform for endurance and an armed UAV for engagement','A manned aircraft for endurance and a HALE vehicle for engagement','A ground radar for endurance and a submarine for engagement','A satellite for endurance and a sensor network for engagement','Slides 32 and 36 support HALE endurance and armed UAV engagement.',[32,36]],
[2,['manned reconnaissance aircraft','UAV'],'An instructor asks which airborne system is the traditional approach and which offers flexible, persistent strike after target identification.','Manned reconnaissance aircraft are traditional; UAVs with payloads give flexible persistent strike','UAVs are traditional; manned aircraft give persistent strike','HALE vehicles are traditional; manned aircraft give persistent strike','Manned aircraft are traditional and give persistent strike','Slides 32 and 35 support this pairing.',[32,35]],
[2,['HALE','UAV','manned reconnaissance aircraft'],'A plan makes four airborne statements. Which one is wrong?','HALE vehicles are limited by pilot endurance to short sorties','UAVs with missiles can engage targets identified through ISR','Manned reconnaissance aircraft have been used since World War I','HALE vehicles can operate extremely high for many hours','Slide 36 says HALE vehicles can operate extremely high for many hours since the pilot has no limitations.',[32,35,36]],
[3,['ground surveillance radar','sensor networks'],'A border post must watch a fixed crossing, later relocate its watch, and add sensors beyond friendly lines. Which mix fits?','Tower-mounted radar, vehicle-mounted radar for relocation, and sensor networks dropped beyond friendly lines','Satellite imagery, submarine sensors, and commercial imagery','HALE vehicles for the crossing, a submarine for relocation, sensor networks for the border','Vehicle radar only, since towers cannot detect crossings','Slides 37-38 cover fixed and mobile radars and sensor networks.',[37,38]],
[3,['terrestrial-based benefits','company UAS'],'A company commander with organic UAS asks which benefits of terrestrial-based ISR apply.','Near-real-time video, local approval for relocation and tasking, and effects after target identification','Unrestricted worldwide coverage, beyond-line-of-sight coverage, and denied-area collection','Unclassified imagery, easy access, and multinational sharing','Silent operation, invisibility to the enemy, and surface-fleet support','Slide 44 lists these terrestrial benefits.',[44]],
[4,['submarine','surface fleet','satellite'],'A naval plan uses a submarine for covert collection, the surface fleet as its foundation, and satellites for huge areas. Which assessment fits the lesson?','Sound: submarines are the most invisible asset, the surface fleet is the backbone, and satellites are incredible for observing huge areas','Flawed: satellites are never useful for maritime ISR because ships move too quickly','Flawed: submarines are the backbone and the surface fleet is the most invisible asset','Flawed: aviation is the backbone of maritime ISR, with the surface fleet as support','Slides 39-41 support each role.',[39,40,41]],
[4,['satellite orbit','maritime ISR'],'An adversary times strait movements to avoid satellite passes. Which adjustment fits the lesson?','Add maritime and airborne assets, because targets can track regular orbit cycles','Rely on satellites more, because orbits guarantee coverage','Drop maritime assets, since satellites cover huge areas','Wait for a satellite pass before acting','Slide 41 warns that targets can track orbit cycles and avoid being seen.',[39,40,41]],
[5,['IMINT','SIGINT','MASINT'],'Analysts need broad-area imagery, intercepts complementing aerial and ground SIGINT, and emitter type and location. Which mapping is correct?','IMINT, SIGINT, MASINT','SIGINT, IMINT, MASINT','MASINT, SIGINT, IMINT','IMINT, MASINT, SIGINT','Slides 41-43 describe each space-based discipline.',[41,42,43]],
[5,['space-based benefits','commercial imagery','company UAS'],'A staff needs a denied area covered, imagery shared with a partner, and near-real-time video. Which mapping fits?','Space-based ISR, commercial imagery, company UAS','Company UAS, space-based ISR, commercial imagery','Commercial imagery, company UAS, space-based ISR','Space-based ISR, company UAS, commercial imagery','Slides 44-45 support this mapping.',[44,45]],
[5,['satellite orbit','SIGINT'],'A staff over-relies on satellites for worldwide coverage. Which two cautions fit the lesson?','Targets can track orbits, and space SIGINT works with aerial and ground SIGINT','Imagery is blurred, and commercial imagery is classified','Satellites cannot see large areas, and targets ignore orbits','Space SIGINT works alone, and orbits are unpredictable','Slides 41-42 give both cautions.',[41,42]],
[6,['timeliness','fusion','accuracy'],'Three reports show a late delivery, a single-source assessment, and a wrong identification. Which principles failed, in order?','Timeliness, fusion, accuracy','Fusion, timeliness, accuracy','Accuracy, fusion, timeliness','Timeliness, accuracy, fusion','Slides 49-51 define these principles.',[49,50,51]],
[6,['fusion','accuracy'],'Which change best improves both accuracy and fusion when identifying a convoy?','Corroborate the IMINT sighting with SIGINT and HUMINT before reporting it','Report immediately from IMINT alone','Wait for coverage of the whole region first','Restrict reporting to one sensor for security','Slides 50-51 support corroboration across sources.',[50,51]],
[6,['timeliness'],'Proposal X skips processing to send raw feeds instantly. Proposal Y collects, processes and disseminates promptly. Which reflects timeliness?','Y, because timeliness covers timely collection, processing and dissemination together','X, because dissemination is the only step timeliness concerns','X, because processing always harms timeliness','Y, because timeliness applies to collection only','Slide 49 names collection, processing and dissemination.',[49]],
[7,['coverage','persistence','flexibility'],'A commander needs the whole area watched, monitoring over days, and quick redirection when the enemy moves. Which principles match, in order?','Coverage, persistence, flexibility','Persistence, coverage, flexibility','Flexibility, persistence, coverage','Coverage, flexibility, persistence','Slides 52-54 define these principles.',[52,53,54]],
[7,['flexibility','coverage'],'A commander redirects sensors after intelligence shows a new enemy route, leaving the old sector unwatched. What should the staff say?','Redirecting fits flexibility, but the plan should still strive for coverage of the area of interest','Redirecting violates persistence entirely and must be reversed','Coverage is met because watching the new route alone satisfies it','Flexibility means the old sector no longer matters','Slides 52 and 54 support both flexibility and coverage.',[52,54]],
[7,['persistence'],'A cell samples a village once a week while enemy movements happen between visits. Which gap and fix fit?','Persistence: sustained, continuous monitoring to detect changes and movements','Coverage: add more villages','Interoperability: adopt allied radios','Security: conceal the visits','Slide 53 defines persistence as continuous monitoring over time.',[53]],
[8,['security','interoperability'],'An allied liaison asks for raw feeds from a sensitive asset. Which approach fits the lesson?','Coordinate with allies while applying strict security to sensitive information and assets','Drop security measures entirely so that interoperability with allies is maximized','Refuse all coordination with allies so that security of the assets is maximized','Let ethics override both','Slides 55-56 support both principles together.',[55,56]],
[8,['ethical considerations','coverage'],'Better coverage would require collection outside the rules of engagement. What does the lesson support?','Ethical considerations govern: collection must follow law, rules of engagement and moral principles','Coverage overrides because comprehensive coverage is the objective','Timeliness overrides because speed matters most','Fusion overrides because more sources are better','Slide 57 places collection under law and rules of engagement.',[52,57]],
[8,['security','interoperability','ethical considerations'],'A feed is compromised, allied units cannot read its format, and collection broke the law. Which principles failed, in order?','Security, interoperability, ethical considerations','Interoperability, security, ethical considerations','Ethical considerations, security, interoperability','Security, ethical considerations, interoperability','Slides 55-57 define these principles.',[55,56,57]],
];


// Distractor rewrites that keep wrong answers as detailed as the key so length gives nothing away.
const PATCH = {
  'medium:2': ['Intelligence means only the continuous observation of one target, so a single feed satisfies the definition', 'Intelligence means only data collected to answer one specific question, which one feed can supply directly', 'One feed is intelligence because modern sensors replace the need for surveillance, reconnaissance and other data'],
  'medium:16': ['Withhold imagery from the partner because commercial products cannot help intelligence capabilities at all', 'Use classified imagery only, because commercial imagery is not relevant to the operations being planned', 'Use SIGINT products instead, because imagery of any kind cannot be shared with multinational partners'],
  'medium:18': ['Sending the first report received straight to the commander so that the assessment is not delayed by checking', 'Assigning all collection to one sensor so that fewer people handle the information and security improves', 'Waiting for full coverage of the whole region before any report is given to the commander for a decision'],
  'medium:19': ['Coverage, which requires the whole area of interest to be watched by the available collection assets', 'Security, which requires strict protection of sensitive information and assets from compromise', 'Fusion, which requires several intelligence sources to be combined into a single product for the commander'],
  'medium:21': ['Persistence: keeping every asset on the original area so that continuous monitoring is never interrupted', 'Coverage: adding more assets to the original area only, so the old route stays fully watched', 'Security: classifying the collection plan more tightly so that the enemy cannot see it change'],
  'hard:2': ['Complete: collection by sensors is all that ISR requires of the staff, since the commander can process it', 'Complete: intelligence is the product of collection, so processing and dissemination links do not affect the result', 'Incomplete only because too few human intelligence teams were used in the collection plan for this brigade'],
  'hard:3': ['Sources are limited to optical imaging alone, and human intelligence teams are not treated as ISR assets', 'Assets are limited to satellites and unmanned aircraft, excluding ground, sea and human intelligence teams', 'Radar and infrared are excluded because ISR relies on electronic communications and optical sources only'],
  'hard:5': ['ISR systems process only structured data and ignore unstructured feeds from small mobile devices and satellites', 'Only large satellites produce insights that commanders can use, because small mobile devices are too limited', 'Faster information flow tends to slow decision-making because staffs become overloaded with feeds'],
  'hard:8': ['UAVs are the traditional approach, while manned reconnaissance aircraft provide flexible persistent strike', 'HALE vehicles are the traditional approach, while manned aircraft provide flexible persistent strike', 'Manned aircraft are the traditional approach and also provide flexible persistent strike after target identification'],
  'hard:12': ['Flawed: satellites are never useful for maritime ISR because ships move too quickly for orbital passes', 'Flawed: submarines are the backbone and the surface fleet is the most invisible asset in the military', 'Flawed: aviation is the backbone of maritime ISR, with the surface fleet playing only a supporting part'],
  'hard:13': ['Rely on satellites more, because their regular orbits guarantee predictable coverage of the strait', 'Drop maritime assets, since satellites already cover huge areas and no other asset is needed', 'Wait for the next satellite pass before acting, because timing collection to orbits removes the risk'],
  'hard:18': ['Report immediately from the IMINT sighting alone so that the commander receives the information sooner', 'Wait until the entire region has been covered before reporting anything about the convoy', 'Restrict reporting to one sensor for security so that fewer sources can be compromised'],
  'hard:19': ['X, because dissemination is the only step of the intelligence flow that timeliness concerns', 'X, because processing always harms timeliness and should be dropped from every ISR flow', 'Y, because timeliness applies to collection only and dissemination is a separate matter'],
  'hard:21': ['Redirecting violates persistence entirely and the sensors must be moved back to the old sector at once', 'Coverage is met because watching the new route alone satisfies the whole area of interest', 'Flexibility means the old sector no longer matters once new intelligence has appeared'],
  'hard:22': ['Coverage: add more villages to the weekly sampling plan so that a larger area is visited', 'Interoperability: adopt allied radios so that the cell can share its weekly findings faster', 'Security: conceal the weekly visits so that the enemy does not notice the cell sampling the village'],
  'hard:24': ['Coverage overrides because comprehensive coverage of the area of interest is the objective of ISR', 'Timeliness overrides because current information matters more than the rules governing collection', 'Fusion overrides because combining more sources is better than staying within the rules of engagement'],
};

// Deterministic placement schedules keep the correct-answer index distribution at 7/6/6/6, 6/7/6/6 and 6/6/7/6.
function schedule(counts, seed) {
  const list = counts.flatMap((count, index) => Array(count).fill(index));
  let state = seed;
  for (let i = list.length - 1; i > 0; i--) {
    state = (state * 1103515245 + 12345) % 2147483648;
    const j = state % (i + 1);
    [list[i], list[j]] = [list[j], list[i]];
  }
  return list;
}

function toBank(rows, difficulty, counts, seed) {
  const slots = schedule(counts, seed);
  return rows.map((row, i) => {
    const [cat, tags, prompt, correct, ...rest] = row;
    const [w1, w2, w3, explanation, slides] = rest;
    const options = [...(PATCH[`${difficulty}:${i + 1}`] ?? [w1, w2, w3])];
    options.splice(slots[i], 0, correct);
    return { id: i + 1, difficulty, category: CATS[cat], tags, prompt, options, answer: slots[i], explanation, sourceSlides: slides };
  });
}

for (const [name, rows, counts, seed] of [['easy', easy, [7, 6, 6, 6], 11], ['medium', medium, [6, 7, 6, 6], 23], ['hard', hard, [6, 6, 7, 6], 37]]) {
  writeFileSync(join(root, 'src', 'questions', `${name}.json`), JSON.stringify(toBank(rows, name, counts, seed), null, 2) + '\n');
}
console.log('Wrote banks', easy.length, medium.length, hard.length);
